server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
          defaultZone: http://eureka2.com:7002/eureka/


  instance:
    hostname: eureka1.com
  server:
    enable-self-preservation: true